### ISSUE TITLE
Problem using "get result_details" with certain result sets 

### ISSUE THREAD

**Issue by munderseth** [testspace-com/testspace-colab#13]
* testspace-colab version: `version 0.1.dev23+g01a1dbc client 2.5.4061`
* Python version: `Python 3.7.3`
* Operating System: `Windows 10`

### Description

Getting `result_details` from Testspace CI Results. Encountering an error on the get. 

### What I Did

Using the following command line:

```
ts-colab client config url $TESTSPACE_TOKEN:@s2.testspace.com/s2technologies:testspace/46_release
ts-colab get result_details  build.92c383b8-0e52-40a5-8984-81d4b2adfc9a -f json -j '$..[cases][:]' -o testspace.json
```
Notes:
- Can insert your own token for $TESTSPACE_TOKEN, the Space is public
- using `-j '$..[cases][:]'` makes no difference

Encounter errors (refer below). 

---
```
URL=https://s2.testspace.com
Traceback (most recent call last):
  File "C:\Users\marku\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\marku\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\marku\Documents\visualstudio\munderseth\my.testspace-colab\env\Scripts\ts-colab.exe\__main__.py", line 9, in <module>
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\click\core.py", line 1025, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\click\core.py", line 955, in main
    rv = self.invoke(ctx)
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\click\core.py", line 1517, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\click\core.py", line 1279, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\click\core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\testspace_colab\cli.py", line 171, in get
    response = client.__getattr__(f"get_{args[0]}")(*pargs, **kwargs)
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\testspace_colab\lib.py", line 154, in get_result_details
    progress_callback=download_progress,
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\testspace_colab\lib.py", line 208, in _load_results
    progress_callback=progress_callback,
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\testspace_colab\lib.py", line 208, in _load_results
    progress_callback=progress_callback,
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\testspace_colab\lib.py", line 208, in _load_results
    progress_callback=progress_callback,
  [Previous line repeated 1 more time]
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\testspace_colab\lib.py", line 189, in _load_results
    xml_tree, progress_callback=progress_callback
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\testspace_colab\utils.py", line
88, in xml_to_json
    xml_data=children, progress_callback=progress_callback
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\testspace_colab\utils.py", line
88, in xml_to_json
    xml_data=children, progress_callback=progress_callback
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\testspace_colab\utils.py", line
83, in xml_to_json
    progress_callback(object_type=xml_data.tag, object_count=1)
  File "c:\users\marku\documents\visualstudio\munderseth\my.testspace-colab\env\lib\site-packages\testspace_colab\lib.py", line 146, in download_progress
    tasks[object_type]["task"],
KeyError: 'comment'
(env)
```

**Comment by lbrack** [comment]
I know the problem - This is good as I was not expecting that - I was planning on silencing those exception but decided otherwise so that such oversight on my end comes to light. Easy fix - I will fix it over the weekend.

**Comment by lbrack** [comment]
okay, can reproduce. I will fix it this weekend.

**Comment by lbrack** [comment]
Re-opening this issue as it is only a partial fix. I guess it was automatically closes by GitHub after the merge

**Comment by lbrack** [comment]
Weird, when accessing ``'projects/s2technologies:testspace/spaces/46_release/results/125227/contents/Tests/cells/insights'``
as resolved by 

![image](https://user-images.githubusercontent.com/14916861/109453007-dad8d280-7a05-11eb-95e4-b61f0e2febc6.png)
in testspace-python, I get a 404 exception
I can access the tests via the UI though
![image](https://user-images.githubusercontent.com/14916861/109453070-fcd25500-7a05-11eb-8c5d-e3ed8f8f4148.png)
All other test suites load without error. 

@munderseth , any idea?

**Comment by munderseth** [comment]
@lbrack try again, I gave you access to the project. The project is `public`, even though the repo is private. Not sure, but maybe using your TS access token "now" it might behave differently.

**Comment by lbrack** [comment]
Well perhaps there is a misunderstanding here. I can download the result
details. Just not that suite.

I will try though - who knows.

Laurent

**Comment by munderseth** [comment]
@lbrack, @ivailop is going to investigate if this is a possible Testspace routing issue due to the fact we have an API that uses `insights`.

**Comment by munderseth** [comment]
@lbrack, @ivailop I have confirmed this is **resolved** on staging now (`47_release`).  The release should be deployed by end of the month (I hope 🤞 ).

**Comment by munderseth** [comment]
Confirmed this issue is resolved. Note there were a couple of issues:
- the `insights` pathname
- reading Content using paging
